--- 
title: "Mapy tematyczne w R"
author: 
- name: "Tomasz Klimanek"
  affiliation: "Katedra Statystyki, Uniwersytet Ekonomiczny w Poznaniu"
  email: tomasz.klimanek@ue.poznan.pl
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Wstęp {-}

Na poprzednich zajęciach przedstawione zostały metody tworzenia map konturowych dla różnych podziałów administracyjnych i statystycznych. W tym celu wykorzystano pakiet **sf**. Natomiast głównym celem niniejszych zajeć będzie stworzenie wykresów mapowych, tzw. kartogramów tj. map tematycznych przedstawiających natęzenie danego zjawiska w poszczególnych jednostkach podziału przestrzennego.

Przedstawienie sekwencyjne tematyki map, tzn. najpierw mapy konturowe, a w dalszej kolejności mapy tematyczne wynika stąd, że często wprowadza się podział zbiorów służących tworzeniu map na dwa rodzaje, w zależności od danych, jakie zawierają:

- dane przestrzenne (służące do narysowania mapy konturowej, zawierające informacje o\ współrzędnych, ich przekształceniach, zastosowanych układach współrzędnych, etc.)
- dane atrybutowe (przechowujące wartości zjawisk, które mają być wyświetlone na mapach w\ powiązaniu z identyfikatorami obiektów mapowych: poligonów, linii, punktów).