install.packages("readxl")
install.packages("sf")
install.packages("dplyr")
install.packages("classInt")
install.packages("RColorBrewer")

library("readxl")
library("sf")
library("dplyr")
library("classInt")
library("RColorBrewer")